version: '3.8'

services:
  mysqldb:
    image: mysql:5.7
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
    ports:
      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
    volumes:
      - db:/var/lib/mysql
    networks:
      - backend
  
  server:
    depends_on:
      - mysqldb
    build: ./server
    restart: unless-stopped
    env_file: ./.env
    volumes:
      - ./server/uploads:/server/uploads
    ports:
      - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT
    environment:
      - DB_HOST=$MYSQLDB_HOST
      - DB_USER=$MYSQLDB_USER
      - DB_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - DB_NAME=$MYSQLDB_DATABASE
      - DB_PORT=$MYSQLDB_DOCKER_PORT
    networks:
      - backend
      - frontend

  client:
    depends_on:
      - server
    build:
      context: ./client
      args:
        - REACT_APP_API_BASE_URL=$CLIENT_API_BASE_URL
        - REACT_APP_API_STATIC_URL=$CLIENT_API_STATIC_URL
    ports:
      - $REACT_LOCAL_PORT:$REACT_DOCKER_PORT
    networks:
      - frontend  
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    env_file: ./.env
    links:
      - mysqldb
    environment:
      PMA_HOST: $MYSQLDB_HOST
      PMA_PORT: $MYSQLDB_DOCKER_PORT
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - $PHPMYADMIN_PORT:80
    networks:
      - backend
    depends_on:
      - mysqldb
volumes:
  db:

networks:
  backend:
  frontend: